### ISSUE TITLE
Issues with Django sitemap framework

### ISSUE THREAD

**Issue by app-generator** [creativetimofficial/black-dashboard-django#2]
By following the official docs of the `sitemap framework` the app serves a blank page. 

https://docs.djangoproject.com/en/3.2/ref/contrib/sitemaps/

[ Follow up issue ]

**Comment by mikeodor** [comment]
still having the issues

**Comment by mikeodor** [comment]
`# sitemaps.py
from django.contrib import sitemaps
from django.urls import reverse


class StaticViewSitemap(sitemaps.Sitemap):

    priority = 0.5
    changefreq = 'daily'

    def items(self):
        return ['proof']

    def location(self, item):
        return reverse(item)

`

**Comment by mikeodor** [comment]
`# sitemaps.py
from django.contrib import sitemaps
from django.urls import reverse


class StaticViewSitemap(sitemaps.Sitemap):

    priority = 0.5
    changefreq = "daily"

    def items(self):
        return ["proof"]

    def location(self, item):
        return reverse(item)

**Comment by mikeodor** [comment]
`# sitemaps.py`
`from django.contrib import sitemaps`
`from django.urls import reverse`
`

`class StaticViewSitemap(sitemaps.Sitemap):`

    priority = 0.5
    changefreq = 'daily'

    def items(self):
        return ['home']

    def location(self, item):
        return reverse(item)`
`

**Comment by mikeodor** [comment]
#urls.py
`from django.contrib.sitemaps.views import sitemap
from django.urls import path

from .sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")),  # Auth routes - login / register
    path("", include("app.urls")),         # UI Kits Html files
    # added sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]
`

**Comment by mikeodor** [comment]
`settings.py`
`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',  # Enable the inner app

    # added below
    'django.contrib.sites',
    'django.contrib.sitemaps',



]
SITE_ID = 1  # define the site id`

**Comment by mikeodor** [comment]
i did the same settings for a new django project without any templates and it worked fine

**Comment by app-generator** [comment]
Hello @mikeodor 

Please update the routing settings as follows: 

```python
urlpatterns = [
path('admin/', admin.site.urls), # Django admin route
path("", include("authentication.urls")), # Auth routes - login / register
path("", include("app.urls")), # UI Kits Html files   # <--- Move this line to be the last rule
# added sitemap
path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
name='django.contrib.sitemaps.views.sitemap'),
]
```

**The patch**

```python
urlpatterns = [
path('admin/', admin.site.urls), # Django admin route
path("", include("authentication.urls")), # Auth routes - login / register
# added sitemap
path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
name='django.contrib.sitemaps.views.sitemap'),
path("", include("app.urls")), # UI Kits Html files    # <-- Now is the last one
]
```

The line basically eats all requests because is a generic loader that serves all pages provided by the design.

Let us know your progress.

**Comment by mikeodor** [comment]
thanks so much it works now

**Comment by app-generator** [comment]
Glad it worked. 
Closing the issue
